install:
    @pip install transformers datasets evaluate scikit-learn
    @pip install nltk==3.6.1
    @pip install accelerate -U
    @pip install torch
    @pip install numpy

install3:
    @pip3 install transformers datasets evaluate scikit-learn
    @pip3 install nltk==3.6.1
    @pip3 install accelerate -U
    @pip3 install torch
    @pip3 install numpy

.PHONY: install install